version: "3.6"

services:

  elasticsearch:
    container_name: es_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk

  kibana:
    container_name: es_kibana
    image: docker.elastic.co/kibana/kibana:7.1.1
    volumes:
      - ./env/dev/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    container_name: es_filebeat
    image: docker.elastic.co/beats/filebeat:7.4.1
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./env/dev/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./log:/var/log/games
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - ENVIRONMENT=dev
    #      - ELASTICSEARCH_HOSTS=elasticsearch:9200
    #      - ELASTICSEARCH_USERNAME=elastic
    #      - ELASTICSEARCH_PASSWORD=changeme
    # disable strict permission checks (filebeat.yml owned by root)
    command: ["--strict.perms=false"]
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  filebeat:
    driver: local
  esdata:
    driver: local